r"""Generate this deployment's secrets and write a ready-to-paste variable block.

Railway (and most managed hosts) offer a "raw editor" that takes a whole
KEY=value block at once. This produces that block: the three secrets already
generated, everything else left blank with a note saying what goes in it.

Run once per environment, from the instagram/ directory:

    ../.venv/Scripts/python.exe scripts/generate_secrets.py

Writes .env.railway, which is gitignored and holds live credentials — treat
it the way you would treat the tokens themselves. Nothing is printed to the
terminal, so the values do not end up in your shell scrollback or in a
screenshot of it.

Refuses to overwrite an existing file. Regenerating secrets is not a harmless
retry: a new ENCRYPTION_KEY makes every stored channel credential unreadable,
and a file half-filled with the values already live on the host is worth more
than a fresh one.
"""

import secrets
import sys
from pathlib import Path

from cryptography.fernet import Fernet

OUTPUT = Path(".env.railway")

TEMPLATE = """\
# Generated by scripts/generate_secrets.py — paste into Railway's raw variable
# editor. Fill in the blanks marked TODO before the first deploy.
#
# Every variable here goes on BOTH the web and worker services, except
# APP_ROLE, which goes on the worker only.

# --- infrastructure -------------------------------------------------------
# TODO: the password you set on the postgres service, and its service name.
# Railway's private hostname is "<service name>.railway.internal".
DATABASE_URL=postgresql+asyncpg://postgres:TODO@postgres.railway.internal:5432/dental
# Railway's own reference syntax — type it literally, do not substitute it.
REDIS_URL=${{{{Redis.REDIS_URL}}}}

# --- secrets (generated; do not regenerate casually) ----------------------
# Encrypts the Instagram/Telegram tokens stored in the database. Must be
# IDENTICAL on web and worker, or the worker generates replies it cannot send.
ENCRYPTION_KEY={encryption_key}
# Signs the dashboard login cookie. Changing it logs everybody out.
SESSION_SECRET_KEY={session_secret_key}
# The string Meta echoes back once when verifying the webhook URL.
WEBHOOK_VERIFY_TOKEN={webhook_verify_token}
# The dashboard runs behind HTTPS here, so the login cookie carries Secure.
SESSION_COOKIE_SECURE=true

# --- the model provider ---------------------------------------------------
# TODO: your OpenAI API key. It writes the replies and makes every embedding,
# so nothing retrieves without it.
OPENAI_API_KEY=TODO

# --- this deployment's public identity ------------------------------------
# TODO: the domain Railway generated for the web service, https, no trailing
# path. Telegram's webhook is registered against this.
PUBLIC_BASE_URL=TODO

# --- first-run provisioning (web service reads these on startup) ----------
# The clinic. Everything below attaches to it.
PROVISION_TENANT_NAME=TODO

# TODO: the @BotFather token. Verified with getMe, stored encrypted, and the
# Telegram webhook is registered for you.
PROVISION_TELEGRAM_BOT_TOKEN=TODO

# The first dashboard login. Created once; changing the password here later
# does NOT change the account's password. Minimum 10 characters.
PROVISION_OPERATOR_USERNAME=admin
PROVISION_OPERATOR_PASSWORD={bootstrap_password}
PROVISION_OPERATOR_NAME=Administrator
PROVISION_OPERATOR_ROLE=operator

# --- Instagram (leave blank until Meta approves the app) ------------------
# The id Meta sends as entry.id in the webhook (17841…), NOT the id
# graph.instagram.com/me returns.
PROVISION_IG_ACCOUNT_ID=
ACCESS_TOKEN=
META_APP_SECRET=TODO

# --- clinic details the assistant may read out ----------------------------
# Both optional. Left empty, the assistant offers a callback rather than
# inventing a number, and declines to give an address at all.
CLINIC_PHONE_NUMBERS=
CLINIC_ADDRESS=
DEFAULT_REPLY_LANGUAGE=Uzbek

# --- one-shot: set for the deploy that loads the FAQs, then remove --------
SEED_FAQS_FROM=
"""


def main() -> None:
    if OUTPUT.exists():
        sys.exit(
            f"{OUTPUT} already exists. Regenerating would mint a new ENCRYPTION_KEY, "
            "which makes every stored channel credential unreadable. Delete it "
            "deliberately if that is what you want."
        )

    OUTPUT.write_text(
        TEMPLATE.format(
            encryption_key=Fernet.generate_key().decode(),
            session_secret_key=secrets.token_urlsafe(32),
            webhook_verify_token=secrets.token_urlsafe(24),
            # Generated rather than left as a TODO: a bootstrap password a
            # human chooses under time pressure is the one that ends up being
            # "admin1234", and this one only has to survive until it is
            # changed from the dashboard.
            bootstrap_password=secrets.token_urlsafe(18),
        ),
        encoding="utf-8",
    )

    # The values themselves are deliberately not printed.
    print(f"Wrote {OUTPUT.resolve()}")
    print("It contains live secrets and is gitignored. Fill in the TODO lines,")
    print("then paste the whole file into Railway's raw variable editor.")


if __name__ == "__main__":
    main()
